/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VendingMachine;

import VendingMachine.config.VendingMachineConfig;
import VendingMachine.model.VendingMachine;
import VendingMachine.view.CustomerInterface;
import VendingMachine.view.StaffInterface;

import java.util.Scanner;


public class App {

    public static void main(String[] args) {
        VendingMachineConfig vendingConfig = ConfigReader.readFoodConfigs("src/main/resources/config.json");

        VendingMachine vendingMachine = new VendingMachine(vendingConfig);

        System.out.println("===========Welcome to vending machine!===========");
        System.out.println("Enter Y to login as staff\nOtherwise, enter anything to continue.");
        Scanner userScanner = new Scanner(System.in);
        while(true) {
            String userInput = userScanner.nextLine();
            if(userInput.compareTo("Y") == 0) {
    			// Staff user interface
    			new StaffInterface(vendingMachine);
    		} else {
                // Customer user interface
                new CustomerInterface(vendingMachine);
            }
            break;
        }
//		userScanner.close();

        //System.out.println(ConfigReader.readRateConfigs("src/test/resources/config.json").getClass().getCanonicalName());
    }
}
